import type { CoupleDemo } from "./seed-demo-types";

export const DEMO_COUPLES: CoupleDemo[] = [
  {
    slug: "priya-rahul",
    primary: {
      firstName: "Priya",
      lastName: "Sharma",
      dob: "1994-06-12",
      gender: "FEMALE",
      phone: "+919845011221",
      email: "priya.sharma@demo.patient",
      language: "en",
    },
    partner: {
      firstName: "Rahul",
      lastName: "Sharma",
      dob: "1991-03-24",
      gender: "MALE",
      phone: "+919845011222",
      email: "rahul.sharma@demo.patient",
      language: "en",
    },
    planType: "IVF",
    planName: "IVF — Standard Journey",
    treatmentKind: "IVF",
    label: "IVF Cycle 01",
    stageName: "Ovarian Stimulation",
    stageIndex: 4,
    coupleStatus: "ACTIVE",
    careLoopActive: true,
    treatmentStatus: "ACTIVE",
    doctorEmail: "ananya@abcfertility.demo",
    coordinatorEmail: "meera@abcfertility.demo",
    registeredDaysAgo: 14,
    tasks: [
      {
        title: "Medication acknowledgement",
        category: "Medication",
        status: "WAITING",
        priority: "HIGH",
        dueOffset: 0,
        assignTo: "patient",
        dueTime: "20:00",
        note: "Gonadotropin stimulation injection scheduled at 8:00 PM. Await patient confirmation.",
      },
      {
        title: "Medication stock & availability check",
        category: "Coordinator",
        status: "IN_PROGRESS",
        priority: "NORMAL",
        dueOffset: 0,
        assignTo: "meera",
      },
      {
        title: "Follicular monitoring ultrasound scan",
        category: "Appointment",
        status: "WAITING",
        priority: "HIGH",
        dueOffset: 1,
        assignTo: "doctor",
        dueTime: "10:00",
      },
      {
        title: "Baseline hormone assessment",
        category: "Investigation",
        status: "COMPLETED",
        priority: "NORMAL",
        dueOffset: -5,
        assignTo: "doctor",
      },
      {
        title: "Signed IVF informed consent",
        category: "Document",
        status: "COMPLETED",
        priority: "HIGH",
        dueOffset: -7,
        assignTo: "meera",
      },
    ],
    appointments: [
      {
        type: "Follicular Monitoring Scan",
        doctorName: "Dr. Ananya Rao",
        room: "Scan Room 1",
        dayOffset: 1,
        hour: 10,
        status: "CONFIRMED",
        notes: "Cycle Day 6 tracking: measure follicle cohort and endometrial thickness",
      },
    ],
    documents: [
      { name: "Consent — IVF Treatment", categoryKey: "CONSENT", status: "REVIEWED" },
      { name: "Baseline Hormones & AMH", categoryKey: "LAB_REPORT", status: "REVIEWED" },
      { name: "Baseline Pelvic Ultrasound", categoryKey: "SCAN_REPORT", status: "REVIEWED" },
    ],
    cycleNotes: "Priya & Rahul active in IVF Stage 5 (Ovarian Stimulation). Day 6 scan scheduled for tomorrow.",
  },
  {
    slug: "anita-rahul",
    primary: {
      firstName: "Anita",
      lastName: "Deshmukh",
      dob: "1993-08-19",
      gender: "FEMALE",
      phone: "+919845033441",
      email: "anita.deshmukh@demo.patient",
      language: "en",
    },
    partner: {
      firstName: "Rahul",
      lastName: "Deshmukh",
      dob: "1990-11-05",
      gender: "MALE",
      phone: "+919845033442",
      email: "rahul.deshmukh@demo.patient",
      language: "en",
    },
    planType: "IVF",
    planName: "IVF — Standard Journey",
    treatmentKind: "IVF",
    label: "IVF Cycle 01",
    stageName: "Follicular Monitoring",
    stageIndex: 5,
    coupleStatus: "ACTIVE",
    careLoopActive: true,
    treatmentStatus: "ACTIVE",
    doctorEmail: "ananya@abcfertility.demo",
    coordinatorEmail: "meera@abcfertility.demo",
    registeredDaysAgo: 18,
    tasks: [
      {
        title: "Review monitoring report",
        category: "Clinical Review",
        status: "WAITING",
        priority: "CLINICAL",
        dueOffset: 0,
        assignTo: "doctor",
        note: "Follicular scan report uploaded: lead follicles 18mm & 17mm. Doctor review required for trigger decision.",
      },
      {
        title: "Follicular monitoring ultrasound scan",
        category: "Appointment",
        status: "COMPLETED",
        priority: "HIGH",
        dueOffset: 0,
        assignTo: "doctor",
      },
    ],
    appointments: [
      {
        type: "Follicular Monitoring Scan",
        doctorName: "Dr. Ananya Rao",
        room: "Scan Room 2",
        dayOffset: 0,
        hour: 9,
        status: "COMPLETED",
        notes: "Scan completed. Follicle measurements entered.",
      },
    ],
    documents: [
      { name: "Consent — IVF Treatment", categoryKey: "CONSENT", status: "REVIEWED" },
      { name: "Day 9 Follicular Monitoring Scan", categoryKey: "SCAN_REPORT", status: "DOCTOR_REVIEW" },
    ],
    cycleNotes: "Follicular monitoring scan completed today. Report uploaded and waiting for Dr. Ananya's clinical trigger decision.",
  },
  {
    slug: "mohit-shru",
    primary: {
      firstName: "Mohit",
      lastName: "Sharma",
      dob: "1992-04-18",
      gender: "MALE",
      phone: "+919812340001",
      email: "mohit.sharma@demo.patient",
      language: "en",
    },
    partner: {
      firstName: "Shru",
      lastName: "Sharma",
      dob: "1995-09-03",
      gender: "FEMALE",
      phone: "+919812340002",
      email: "shru.sharma@demo.patient",
      language: "hi",
    },
    planType: "IVF",
    planName: "IVF Basic",
    treatmentKind: "IVF",
    label: "IVF-2026-NEW",
    stageName: "Consultation",
    stageIndex: 0,
    coupleStatus: "ACTIVE",
    careLoopActive: true,
    treatmentStatus: "ACTIVE",
    doctorEmail: "ananya@abcfertility.demo",
    coordinatorEmail: "meera@abcfertility.demo",
    registeredDaysAgo: 3,
    tasks: [
      {
        title: "Complete intake forms",
        category: "Document",
        status: "IN_PROGRESS",
        priority: "NORMAL",
        dueOffset: 1,
        assignTo: "meera",
      },
      {
        title: "Book IVF counselling session",
        category: "Appointment",
        status: "WAITING",
        priority: "HIGH",
        dueOffset: 2,
        assignTo: "meera",
      },
      {
        title: "Review baseline labs order",
        category: "Investigation",
        status: "WAITING",
        priority: "NORMAL",
        dueOffset: 3,
        assignTo: "doctor",
      },
    ],
    appointments: [
      {
        type: "IVF Consultation",
        doctorName: "Dr. Ananya Rao",
        room: "Room 2",
        dayOffset: 2,
        hour: 10,
        status: "CONFIRMED",
        notes: "First consultation for IVF Basic plan",
      },
    ],
    documents: [
      { name: "Consent — IVF Treatment", categoryKey: "CONSENT", status: "AWAITING_UPLOAD" },
      { name: "ID Proof", categoryKey: "OTHER", status: "UPLOADED" },
    ],
    cycleNotes: "Newly registered couple starting IVF counselling.",
  },
  {
    slug: "arjun-neha",
    primary: {
      firstName: "Arjun",
      lastName: "Kapoor",
      dob: "1989-11-22",
      gender: "MALE",
      phone: "+919823450011",
      email: "arjun.kapoor@demo.patient",
      language: "hi",
    },
    partner: {
      firstName: "Neha",
      lastName: "Kapoor",
      dob: "1993-06-14",
      gender: "FEMALE",
      phone: "+919823450012",
      email: "neha.kapoor@demo.patient",
      language: "en",
    },
    planType: "IVF",
    planName: "IVF Standard Journey",
    treatmentKind: "IVF",
    label: "IVF-2026-001",
    stageName: "Stimulation",
    stageIndex: 2,
    coupleStatus: "ACTIVE",
    careLoopActive: true,
    treatmentStatus: "ACTIVE",
    doctorEmail: "ravi@abcfertility.demo",
    coordinatorEmail: "meera@abcfertility.demo",
    registeredDaysAgo: 45,
    tasks: [
      {
        title: "Follicular scan — Day 8",
        category: "Investigation",
        status: "WAITING",
        priority: "HIGH",
        dueOffset: 0,
        assignTo: "meera",
      },
      {
        title: "Follicular scan — Day 10",
        category: "Investigation",
        status: "WAITING",
        priority: "HIGH",
        dueOffset: 2,
        assignTo: "meera",
      },
      {
        title: "Stimulation medication check-in",
        category: "Medication",
        status: "IN_PROGRESS",
        priority: "CLINICAL",
        dueOffset: 1,
        assignTo: "doctor",
      },
    ],
    appointments: [
      {
        type: "Follicular Monitoring Scan",
        doctorName: "Dr. Rahul Menon",
        room: "Scan 1",
        dayOffset: 0,
        hour: 9,
        status: "CONFIRMED",
      },
      {
        type: "Stimulation Review",
        doctorName: "Dr. Rahul Menon",
        room: "Room 3",
        dayOffset: 2,
        hour: 11,
        status: "WAITING",
      },
    ],
    documents: [
      { name: "Day 6 Follicular Scan Report", categoryKey: "SCAN_REPORT", status: "REVIEWED" },
      { name: "Hormone Panel — E2/LH/P4", categoryKey: "LAB_REPORT", status: "DOCTOR_REVIEW" },
      { name: "Stimulation Prescription", categoryKey: "PRESCRIPTION", status: "UPLOADED" },
    ],
    cycleNotes: "Active stimulation; follicular scans scheduled Day 8 and Day 10.",
  },
  {
    slug: "rohan-priya",
    primary: {
      firstName: "Rohan",
      lastName: "Mehta",
      dob: "1990-02-07",
      gender: "MALE",
      phone: "+919834560021",
      email: "rohan.mehta@demo.patient",
      language: "gu",
    },
    partner: {
      firstName: "Priya",
      lastName: "Mehta",
      dob: "1994-12-19",
      gender: "FEMALE",
      phone: "+919834560022",
      email: "priya.mehta@demo.patient",
      language: "hi",
    },
    planType: "IUI",
    planName: "IUI Evaluation Journey",
    treatmentKind: "IUI",
    label: "IUI-2026-001",
    stageName: "Evaluation",
    stageIndex: 1,
    coupleStatus: "ON_HOLD",
    careLoopActive: true,
    treatmentStatus: "NEEDS_ATTENTION",
    doctorEmail: "priya@abcfertility.demo",
    coordinatorEmail: "meera@abcfertility.demo",
    registeredDaysAgo: 28,
    tasks: [
      {
        title: "Upload hormone report (AMH, TSH, FSH)",
        category: "Document",
        status: "OVERDUE",
        priority: "HIGH",
        dueOffset: -3,
        assignTo: "meera",
      },
      {
        title: "Partner semen analysis follow-up",
        category: "Investigation",
        status: "WAITING",
        priority: "NORMAL",
        dueOffset: 1,
        assignTo: "meera",
      },
      {
        title: "Coordinator callback — missing labs",
        category: "Follow-up",
        status: "ESCALATED",
        priority: "HIGH",
        dueOffset: -1,
        assignTo: "meera",
      },
    ],
    escalations: [
      {
        type: "MISSING_REPORT",
        severity: "HIGH",
        reason: "Hormone report overdue; IUI evaluation cannot proceed.",
      },
    ],
    appointments: [
      {
        type: "IUI Evaluation Review",
        doctorName: "Dr. Priya Nair",
        room: "Room 1",
        dayOffset: 4,
        hour: 15,
        status: "WAITING",
        notes: "On hold pending hormone report upload",
      },
    ],
    documents: [
      { name: "Hormone Report — AMH/TSH/FSH", categoryKey: "LAB_REPORT", status: "AWAITING_UPLOAD" },
      { name: "Baseline Ultrasound", categoryKey: "SCAN_REPORT", status: "UPLOADED" },
    ],
    cycleNotes: "Cycle on hold — overdue hormone report blocking evaluation.",
  },
  {
    slug: "vikram-anjali",
    primary: {
      firstName: "Vikram",
      lastName: "Rao",
      dob: "1988-08-30",
      gender: "MALE",
      phone: "+919845670031",
      email: "vikram.rao@demo.patient",
      language: "kn",
    },
    partner: {
      firstName: "Anjali",
      lastName: "Rao",
      dob: "1991-01-25",
      gender: "FEMALE",
      phone: "+919845670032",
      email: "anjali.rao@demo.patient",
      language: "en",
    },
    planType: "IVF",
    planName: "IVF Advanced Journey",
    treatmentKind: "IVF",
    label: "IVF-2026-002",
    stageName: "Embryo Transfer",
    stageIndex: 4,
    coupleStatus: "ACTIVE",
    careLoopActive: true,
    treatmentStatus: "ACTIVE",
    doctorEmail: "ananya@abcfertility.demo",
    coordinatorEmail: "meera@abcfertility.demo",
    registeredDaysAgo: 72,
    tasks: [
      {
        title: "Confirm embryo transfer consent",
        category: "Document",
        status: "IN_PROGRESS",
        priority: "CLINICAL",
        dueOffset: 0,
        assignTo: "doctor",
      },
      {
        title: "Pre-transfer medication check",
        category: "Medication",
        status: "WAITING",
        priority: "HIGH",
        dueOffset: 1,
        assignTo: "meera",
      },
      {
        title: "Arrange transfer OT slot",
        category: "Procedure",
        status: "WAITING",
        priority: "NORMAL",
        dueOffset: 1,
        assignTo: "meera",
      },
    ],
    appointments: [
      {
        type: "Embryo Transfer",
        doctorName: "Dr. Ananya Rao",
        room: "OT",
        dayOffset: 1,
        hour: 8,
        status: "CONFIRMED",
      },
      {
        type: "Transfer Prep Counselling",
        doctorName: "Dr. Ananya Rao",
        room: "Room 2",
        dayOffset: 0,
        hour: 16,
        status: "WAITING",
      },
    ],
    documents: [
      { name: "Embryo Transfer Consent", categoryKey: "CONSENT", status: "DOCTOR_REVIEW" },
      { name: "Embryo Grading Report", categoryKey: "TREATMENT_DOCUMENT", status: "REVIEWED" },
      { name: "Endometrial Prep Scan", categoryKey: "SCAN_REPORT", status: "REVIEWED" },
    ],
    cycleNotes: "Scheduled for embryo transfer; consent and OT prep in progress.",
  },
  {
    slug: "karan-riya",
    primary: {
      firstName: "Karan",
      lastName: "Shah",
      dob: "1991-05-11",
      gender: "MALE",
      phone: "+919856780041",
      email: "karan.shah@demo.patient",
      language: "gu",
    },
    partner: {
      firstName: "Riya",
      lastName: "Shah",
      dob: "1994-10-02",
      gender: "FEMALE",
      phone: "+919856780042",
      email: "riya.shah@demo.patient",
      language: "en",
    },
    planType: "FET",
    planName: "FET Journey",
    treatmentKind: "FET",
    label: "FET-2026-003",
    stageName: "Preparation",
    stageIndex: 1,
    coupleStatus: "ON_HOLD",
    careLoopActive: false,
    treatmentStatus: "CANCELLED",
    doctorEmail: "ravi@abcfertility.demo",
    coordinatorEmail: "meera@abcfertility.demo",
    registeredDaysAgo: 55,
    tasks: [
      {
        title: "Pause FET medication schedule",
        category: "Medication",
        status: "CANCELLED",
        priority: "NORMAL",
        dueOffset: -5,
        assignTo: "meera",
      },
      {
        title: "Document cycle cancel reason",
        category: "Follow-up",
        status: "COMPLETED",
        priority: "LOW",
        dueOffset: -2,
        assignTo: "meera",
      },
      {
        title: "Schedule restart counselling",
        category: "Appointment",
        status: "WAITING",
        priority: "NORMAL",
        dueOffset: 14,
        assignTo: "doctor",
      },
    ],
    appointments: [
      {
        type: "FET Preparation Visit",
        doctorName: "Dr. Rahul Menon",
        room: "Room 3",
        dayOffset: -4,
        hour: 12,
        status: "CANCELLED",
        notes: "Cycle cancelled at patient request",
      },
    ],
    documents: [
      { name: "FET Consent", categoryKey: "CONSENT", status: "UPLOADED" },
      { name: "Frozen Embryo Inventory Note", categoryKey: "TREATMENT_DOCUMENT", status: "REVIEWED" },
    ],
    cycleNotes: "FET preparation cancelled; care loop paused pending restart.",
  },
  {
    slug: "amit-sneha",
    primary: {
      firstName: "Amit",
      lastName: "Verma",
      dob: "1987-03-16",
      gender: "MALE",
      phone: "+919867890051",
      email: "amit.verma@demo.patient",
      language: "hi",
    },
    partner: {
      firstName: "Sneha",
      lastName: "Verma",
      dob: "1990-07-28",
      gender: "FEMALE",
      phone: "+919867890052",
      email: "sneha.verma@demo.patient",
      language: "en",
    },
    planType: "IVF",
    planName: "Post Transfer Monitoring",
    treatmentKind: "IVF",
    label: "IVF-2026-004",
    stageName: "Pregnancy Test",
    stageIndex: 6,
    coupleStatus: "ACTIVE",
    careLoopActive: true,
    treatmentStatus: "ACTIVE",
    doctorEmail: "priya@abcfertility.demo",
    coordinatorEmail: "meera@abcfertility.demo",
    registeredDaysAgo: 90,
    tasks: [
      {
        title: "Schedule beta-hCG blood test",
        category: "Investigation",
        status: "WAITING",
        priority: "HIGH",
        dueOffset: 1,
        assignTo: "meera",
      },
      {
        title: "Post-transfer symptom check-in",
        category: "Follow-up",
        status: "IN_PROGRESS",
        priority: "NORMAL",
        dueOffset: 0,
        assignTo: "meera",
      },
      {
        title: "Review luteal support compliance",
        category: "Medication",
        status: "WAITING",
        priority: "CLINICAL",
        dueOffset: 2,
        assignTo: "doctor",
      },
    ],
    appointments: [
      {
        type: "Beta-hCG Pregnancy Test",
        doctorName: "Dr. Priya Nair",
        room: "Lab Desk",
        dayOffset: 1,
        hour: 8,
        status: "CONFIRMED",
      },
      {
        type: "Post-transfer Follow-up",
        doctorName: "Dr. Priya Nair",
        room: "Room 1",
        dayOffset: 3,
        hour: 14,
        status: "WAITING",
      },
    ],
    documents: [
      { name: "Transfer Day Summary", categoryKey: "TREATMENT_DOCUMENT", status: "REVIEWED" },
      { name: "Luteal Support Prescription", categoryKey: "PRESCRIPTION", status: "UPLOADED" },
      { name: "Beta-hCG Result", categoryKey: "LAB_REPORT", status: "AWAITING_UPLOAD" },
    ],
    cycleNotes: "Post transfer; awaiting pregnancy test and luteal support monitoring.",
  },
  {
    slug: "nikhil-aisha",
    primary: {
      firstName: "Nikhil",
      lastName: "Joshi",
      dob: "1993-09-09",
      gender: "MALE",
      phone: "+919878900061",
      email: "nikhil.joshi@demo.patient",
      language: "hi",
    },
    partner: {
      firstName: "Aisha",
      lastName: "Joshi",
      dob: "1996-04-21",
      gender: "FEMALE",
      phone: "+919878900062",
      email: "aisha.joshi@demo.patient",
      language: "en",
    },
    planType: "IUI",
    planName: "IUI Standard Journey",
    treatmentKind: "IUI",
    label: "IUI-2026-002",
    stageName: "Post Procedure",
    stageIndex: 5,
    coupleStatus: "ON_HOLD",
    careLoopActive: true,
    treatmentStatus: "NEEDS_ATTENTION",
    doctorEmail: "priya@abcfertility.demo",
    coordinatorEmail: "meera@abcfertility.demo",
    registeredDaysAgo: 38,
    tasks: [
      {
        title: "Attend post-IUI follow-up",
        category: "Appointment",
        status: "OVERDUE",
        priority: "HIGH",
        dueOffset: -2,
        assignTo: "meera",
      },
      {
        title: "Confirm progesterone support",
        category: "Medication",
        status: "WAITING",
        priority: "NORMAL",
        dueOffset: 0,
        assignTo: "doctor",
      },
      {
        title: "Reschedule missed follow-up",
        category: "Follow-up",
        status: "ESCALATED",
        priority: "HIGH",
        dueOffset: -1,
        assignTo: "meera",
      },
    ],
    escalations: [
      {
        type: "APPOINTMENT",
        severity: "MEDIUM",
        reason: "Post-procedure follow-up overdue; patient did not attend.",
      },
    ],
    appointments: [
      {
        type: "IUI Post-Procedure Follow-up",
        doctorName: "Dr. Priya Nair",
        room: "Room 2",
        dayOffset: -2,
        hour: 11,
        status: "NO_SHOW",
      },
      {
        type: "IUI Follow-up (Reschedule)",
        doctorName: "Dr. Priya Nair",
        room: "Room 2",
        dayOffset: 2,
        hour: 11,
        status: "WAITING",
      },
    ],
    documents: [
      { name: "IUI Procedure Note", categoryKey: "TREATMENT_DOCUMENT", status: "REVIEWED" },
      { name: "Semen Wash Report", categoryKey: "SEMEN_ANALYSIS", status: "REVIEWED" },
    ],
    cycleNotes: "Post IUI; overdue follow-up escalated as appointment issue.",
  },
  {
    slug: "suresh-divya",
    primary: {
      firstName: "Suresh",
      lastName: "Kumar",
      dob: "1985-12-04",
      gender: "MALE",
      phone: "+919889010071",
      email: "suresh.kumar@demo.patient",
      language: "ta",
    },
    partner: {
      firstName: "Divya",
      lastName: "Kumar",
      dob: "1988-06-17",
      gender: "FEMALE",
      phone: "+919889010072",
      email: "divya.kumar@demo.patient",
      language: "ta",
    },
    planType: "IVF",
    planName: "IVF Standard Journey",
    treatmentKind: "IVF",
    label: "IVF-2026-005",
    stageName: "Completed",
    stageIndex: 6,
    coupleStatus: "COMPLETED",
    careLoopActive: false,
    treatmentStatus: "COMPLETED",
    doctorEmail: "ananya@abcfertility.demo",
    coordinatorEmail: "meera@abcfertility.demo",
    registeredDaysAgo: 180,
    tasks: [
      {
        title: "Archive cycle documents",
        category: "Document",
        status: "COMPLETED",
        priority: "LOW",
        dueOffset: -10,
        assignTo: "meera",
      },
      {
        title: "Discharge counselling completed",
        category: "Follow-up",
        status: "COMPLETED",
        priority: "NORMAL",
        dueOffset: -7,
        assignTo: "doctor",
      },
      {
        title: "Close care loop",
        category: "Follow-up",
        status: "COMPLETED",
        priority: "LOW",
        dueOffset: -5,
        assignTo: "meera",
      },
    ],
    appointments: [
      {
        type: "Pregnancy Confirmation Visit",
        doctorName: "Dr. Ananya Rao",
        room: "Room 1",
        dayOffset: -14,
        hour: 10,
        status: "COMPLETED",
      },
      {
        type: "Cycle Discharge Review",
        doctorName: "Dr. Ananya Rao",
        room: "Room 1",
        dayOffset: -7,
        hour: 15,
        status: "COMPLETED",
      },
    ],
    documents: [
      { name: "Final Beta-hCG Report", categoryKey: "LAB_REPORT", status: "REVIEWED" },
      { name: "Discharge Summary", categoryKey: "TREATMENT_DOCUMENT", status: "REVIEWED" },
      { name: "IVF Consent Pack", categoryKey: "CONSENT", status: "REVIEWED" },
    ],
    cycleNotes: "IVF journey completed successfully; care loop closed.",
  },
  {
    slug: "aditya-pooja",
    primary: {
      firstName: "Aditya",
      lastName: "Menon",
      dob: "1994-01-13",
      gender: "MALE",
      phone: "+919890120081",
      email: "aditya.menon@demo.patient",
      language: "ml",
    },
    partner: {
      firstName: "Pooja",
      lastName: "Menon",
      dob: "1997-08-05",
      gender: "FEMALE",
      phone: "+919890120082",
      email: "pooja.menon@demo.patient",
      language: "en",
    },
    planType: "FERTILITY_EVALUATION",
    planName: "Initial Fertility Evaluation",
    treatmentKind: "EVALUATION",
    label: "EVAL-2026-001",
    stageName: "Initial Evaluation",
    stageIndex: 0,
    coupleStatus: "ACTIVE",
    careLoopActive: true,
    treatmentStatus: "ACTIVE",
    doctorEmail: "ravi@abcfertility.demo",
    coordinatorEmail: "meera@abcfertility.demo",
    registeredDaysAgo: 7,
    tasks: [
      {
        title: "Order baseline hormone panel",
        category: "Investigation",
        status: "IN_PROGRESS",
        priority: "HIGH",
        dueOffset: 1,
        assignTo: "doctor",
      },
      {
        title: "Book AMH + ultrasound package",
        category: "Appointment",
        status: "WAITING",
        priority: "NORMAL",
        dueOffset: 2,
        assignTo: "meera",
      },
      {
        title: "Collect medical history questionnaire",
        category: "Document",
        status: "WAITING",
        priority: "NORMAL",
        dueOffset: 0,
        assignTo: "meera",
      },
    ],
    appointments: [
      {
        type: "Initial Fertility Evaluation",
        doctorName: "Dr. Rahul Menon",
        room: "Room 3",
        dayOffset: 2,
        hour: 10,
        status: "CONFIRMED",
      },
    ],
    documents: [
      { name: "Medical History Form", categoryKey: "OTHER", status: "AWAITING_UPLOAD" },
      { name: "Prior Lab Reports", categoryKey: "LAB_REPORT", status: "UPLOADED" },
    ],
    cycleNotes: "New evaluation couple; baseline workup just started.",
  },
  {
    slug: "manish-kavya",
    primary: {
      firstName: "Manish",
      lastName: "Patel",
      dob: "1986-10-27",
      gender: "MALE",
      phone: "+919901230091",
      email: "manish.patel@demo.patient",
      language: "gu",
    },
    partner: {
      firstName: "Kavya",
      lastName: "Patel",
      dob: "1989-02-14",
      gender: "FEMALE",
      phone: "+919901230092",
      email: "kavya.patel@demo.patient",
      language: "hi",
    },
    planType: "IVF",
    planName: "IVF Standard Journey",
    treatmentKind: "IVF",
    label: "IVF-2026-006",
    stageName: "Medication",
    stageIndex: 2,
    coupleStatus: "ON_HOLD",
    careLoopActive: false,
    treatmentStatus: "CANCELLED",
    doctorEmail: "ananya@abcfertility.demo",
    coordinatorEmail: "meera@abcfertility.demo",
    registeredDaysAgo: 64,
    tasks: [
      {
        title: "Stop stimulation medication",
        category: "Medication",
        status: "CANCELLED",
        priority: "HIGH",
        dueOffset: -8,
        assignTo: "doctor",
      },
      {
        title: "Record cancellation counselling",
        category: "Follow-up",
        status: "COMPLETED",
        priority: "NORMAL",
        dueOffset: -6,
        assignTo: "meera",
      },
      {
        title: "Refund / billing note for paused cycle",
        category: "Payment",
        status: "WAITING",
        priority: "LOW",
        dueOffset: 5,
        assignTo: "meera",
      },
    ],
    appointments: [
      {
        type: "Medication Review",
        doctorName: "Dr. Ananya Rao",
        room: "Room 2",
        dayOffset: -8,
        hour: 13,
        status: "CANCELLED",
        notes: "IVF medication phase cancelled",
      },
    ],
    documents: [
      { name: "Cancellation Counselling Note", categoryKey: "TREATMENT_DOCUMENT", status: "REVIEWED" },
      { name: "Stimulation Prescription (voided)", categoryKey: "PRESCRIPTION", status: "REJECTED" },
    ],
    cycleNotes: "IVF medication stage cancelled; care loop inactive.",
  },
];
