import { defaultAppointmentSettings, defaultClinicSchedule, newId } from "./catalog";
import type { DoctorActivity, DoctorProfile } from "./types";

function activity(kind: DoctorActivity["kind"], message: string, at: string): DoctorActivity {
  return { id: newId("act"), kind, message, at };
}

const now = "2026-08-01T09:00:00.000Z";

export const SEED_DOCTORS: DoctorProfile[] = [
  {
    id: "doc_ananya",
    staffUserId: "u1",
    status: "active",
    isDraft: false,
    firstName: "Ananya",
    lastName: "Rao",
    displayName: "Dr. Ananya Rao",
    gender: "Female",
    dateOfBirth: "1986-04-12",
    phone: "+91 98450 10001",
    email: "ananya@abcfertility.demo",
    alternatePhone: "+91 98450 10002",
    employeeId: "DOC-001",
    registrationNumber: "KMC-45218",
    registrationAuthority: "Karnataka Medical Council",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    designation: "Senior Fertility Specialist",
    department: "Reproductive Medicine",
    primarySpecialty: "Reproductive Medicine",
    subSpecialties: ["IVF", "IUI", "FET", "Fertility Evaluation"],
    yearsExperience: 14,
    yearsInSpecialty: 10,
    consultationTypes: ["In-clinic", "Online"],
    languages: ["English", "Hindi", "Kannada"],
    professionalBio:
      "Dr. Ananya Rao specialises in evidence-based fertility care with a focus on personalised IVF and FET protocols. She partners closely with Care Loop coordinators to keep couples informed at every treatment milestone.",
    shortIntro: "Reproductive Medicine Specialist focused on IVF and patient-centred fertility care.",
    clinicalInterests: "Embryo transfer optimisation, unexplained infertility, FET protocols",
    expertise: ["IVF", "IUI", "FET", "Fertility Evaluation", "Reproductive Medicine"],
    services: ["Initial Consultation", "Follow-up Consultation", "Follicular Monitoring", "Cycle Review"],
    procedures: ["IUI", "Oocyte Retrieval", "Embryo Transfer", "FET", "ICSI"],
    qualifications: [
      {
        id: "q_a1",
        degree: "MBBS",
        specialization: "Medicine",
        institution: "Bangalore Medical College",
        university: "RGUHS",
        location: "Bangalore",
        startYear: "2004",
        endYear: "2009",
        description: "Undergraduate medical training",
      },
      {
        id: "q_a2",
        degree: "MD",
        specialization: "Obstetrics & Gynaecology",
        institution: "St. John's Medical College",
        university: "RGUHS",
        location: "Bangalore",
        startYear: "2010",
        endYear: "2013",
        description: "Postgraduate specialisation",
      },
      {
        id: "q_a3",
        degree: "Fellowship",
        specialization: "Reproductive Medicine",
        institution: "National Board Fellowship Centre",
        university: "NBE",
        location: "Bangalore",
        startYear: "2014",
        endYear: "2016",
        description: "Advanced fertility training",
      },
    ],
    experience: [
      {
        id: "e_a1",
        organization: "ABC Fertility Centre",
        position: "Senior Fertility Specialist",
        department: "Reproductive Medicine",
        startDate: "2020-01",
        endDate: "",
        currentlyWorking: true,
        description: "Leads IVF and FET programmes across Bangalore clinic.",
        responsibilities: "Clinical protocols, embryo transfer decisions, Care Loop clinical oversight",
      },
      {
        id: "e_a2",
        organization: "City Women's Hospital",
        position: "Consultant Gynaecologist",
        department: "Obstetrics & Gynaecology",
        startDate: "2016-06",
        endDate: "2019-12",
        currentlyWorking: false,
        description: "Managed fertility evaluations and obstetric care.",
        responsibilities: "Consultations, procedures, multidisciplinary case reviews",
      },
    ],
    weeklySchedule: defaultClinicSchedule(),
    appointmentSettings: defaultAppointmentSettings(),
    leaves: [],
    blockedTimes: [],
    documents: [
      {
        id: "d_a1",
        kind: "medical_registration",
        name: "KMC Registration Certificate",
        uploadedAt: now,
      },
    ],
    activity: [
      activity("created", "Doctor profile created", now),
      activity("activated", "Doctor activated for appointments", now),
      activity("availability_updated", "Weekly availability configured", now),
    ],
    locationId: "blr",
    locationName: "Bangalore",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "doc_ravi",
    staffUserId: "u2",
    status: "active",
    isDraft: false,
    firstName: "Ravi",
    lastName: "Menon",
    displayName: "Dr. Ravi Menon",
    gender: "Male",
    dateOfBirth: "1982-09-03",
    phone: "+91 98450 20001",
    email: "ravi@abcfertility.demo",
    alternatePhone: "",
    employeeId: "DOC-002",
    registrationNumber: "TMC-33891",
    registrationAuthority: "Travancore-Cochin Medical Council",
    country: "India",
    state: "Kerala",
    city: "Kochi",
    designation: "Reproductive Endocrinologist",
    department: "Reproductive Medicine",
    primarySpecialty: "Reproductive Medicine",
    subSpecialties: ["IUI", "Male Infertility", "Reproductive Endocrinology"],
    yearsExperience: 16,
    yearsInSpecialty: 12,
    consultationTypes: ["In-clinic", "Hybrid"],
    languages: ["English", "Malayalam", "Hindi"],
    professionalBio:
      "Dr. Ravi Menon focuses on reproductive endocrinology and male-factor infertility, supporting couples through IUI and complex endocrine workups.",
    shortIntro: "Reproductive endocrinologist with expertise in IUI and male infertility.",
    clinicalInterests: "Male infertility, ovulation disorders, endocrine optimisation",
    expertise: ["IUI", "Male Infertility", "Reproductive Medicine", "Ovulation Induction"],
    services: ["Initial Consultation", "Follow-up Consultation", "Counselling", "Second Opinion"],
    procedures: ["IUI", "Diagnostic Laparoscopy", "Hysteroscopy"],
    qualifications: [
      {
        id: "q_r1",
        degree: "MBBS",
        specialization: "Medicine",
        institution: "Government Medical College",
        university: "KUHS",
        location: "Thrissur",
        startYear: "2001",
        endYear: "2006",
        description: "",
      },
      {
        id: "q_r2",
        degree: "MD",
        specialization: "Endocrinology",
        institution: "Amrita Institute",
        university: "Amrita Vishwa Vidyapeetham",
        location: "Kochi",
        startYear: "2008",
        endYear: "2011",
        description: "",
      },
    ],
    experience: [
      {
        id: "e_r1",
        organization: "ABC Fertility Centre",
        position: "Reproductive Endocrinologist",
        department: "Reproductive Medicine",
        startDate: "2018-03",
        endDate: "",
        currentlyWorking: true,
        description: "Leads endocrine and IUI pathways for Kochi and Bangalore referrals.",
        responsibilities: "Consultations, protocol design, partner investigations",
      },
    ],
    weeklySchedule: (() => {
      const s = defaultClinicSchedule();
      s.friday = { enabled: false, slots: [] };
      return s;
    })(),
    appointmentSettings: {
      ...defaultAppointmentSettings(),
      consultationMinutes: 25,
      followUpMinutes: 15,
    },
    leaves: [
      {
        id: "leave_r1",
        date: "2026-09-05",
        fullDay: true,
        type: "conference",
        reason: "Fertility conference",
        notes: "Out of clinic for academic conference",
        createdAt: now,
      },
    ],
    blockedTimes: [],
    documents: [],
    activity: [
      activity("created", "Doctor profile created", now),
      activity("activated", "Doctor activated for appointments", now),
      activity("leave_added", "Conference leave added for 5 Sep 2026", now),
    ],
    locationId: "kochi",
    locationName: "Kochi",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "doc_priya",
    status: "on_leave",
    isDraft: false,
    firstName: "Priya",
    lastName: "Nair",
    displayName: "Dr. Priya Nair",
    gender: "Female",
    dateOfBirth: "1988-11-21",
    phone: "+91 98450 30001",
    email: "priya@abcfertility.demo",
    alternatePhone: "",
    employeeId: "DOC-003",
    registrationNumber: "TNC-22109",
    registrationAuthority: "Tamil Nadu Medical Council",
    country: "India",
    state: "Tamil Nadu",
    city: "Chennai",
    designation: "Consultant Gynaecologist",
    department: "Gynaecology",
    primarySpecialty: "Gynaecology",
    subSpecialties: ["Pregnancy Care", "Fertility Evaluation"],
    yearsExperience: 9,
    yearsInSpecialty: 6,
    consultationTypes: ["In-clinic"],
    languages: ["English", "Tamil", "Hindi"],
    professionalBio:
      "Dr. Priya Nair provides gynaecology and early fertility evaluation services for the Chennai clinic.",
    shortIntro: "Consultant gynaecologist supporting pregnancy care and fertility evaluation.",
    clinicalInterests: "Early pregnancy care, fertility workups",
    expertise: ["Pregnancy Care", "Fertility Evaluation", "Reproductive Medicine"],
    services: ["Initial Consultation", "Follow-up Consultation", "Ultrasound Scan"],
    procedures: ["Hysteroscopy", "Endometrial Biopsy"],
    qualifications: [
      {
        id: "q_p1",
        degree: "MBBS",
        specialization: "Medicine",
        institution: "Madras Medical College",
        university: "TN MGR Medical University",
        location: "Chennai",
        startYear: "2006",
        endYear: "2011",
        description: "",
      },
      {
        id: "q_p2",
        degree: "MS",
        specialization: "Obstetrics & Gynaecology",
        institution: "Stanley Medical College",
        university: "TN MGR Medical University",
        location: "Chennai",
        startYear: "2012",
        endYear: "2015",
        description: "",
      },
    ],
    experience: [
      {
        id: "e_p1",
        organization: "ABC Fertility Centre",
        position: "Consultant Gynaecologist",
        department: "Gynaecology",
        startDate: "2021-08",
        endDate: "",
        currentlyWorking: true,
        description: "Supports Chennai clinic consultations and evaluations.",
        responsibilities: "OPD, scans, Care Loop clinical handoffs",
      },
    ],
    weeklySchedule: defaultClinicSchedule(),
    appointmentSettings: defaultAppointmentSettings(),
    leaves: [
      {
        id: "leave_p1",
        date: "2026-08-25",
        endDate: "2026-09-10",
        fullDay: true,
        type: "personal",
        reason: "Personal leave",
        notes: "Extended personal leave",
        createdAt: now,
      },
    ],
    blockedTimes: [],
    documents: [],
    activity: [
      activity("created", "Doctor profile created", now),
      activity("leave_added", "Personal leave period added", now),
    ],
    locationId: "chennai",
    locationName: "Chennai",
    createdAt: now,
    updatedAt: now,
  },
];
